### ISSUE TITLE
Error al compilar en windows 10

### ISSUE THREAD

**Issue by Alexis-18** [orangeloops/public-ol-web-template#26]
Al tratar de levantar el proyecto da un error de compilación como se muestra en la imagen. 

![errorWindows](https://user-images.githubusercontent.com/54026070/63172767-d2cc6400-c014-11e9-9251-996a94e38ea4.PNG)

Utilizando cross-env se pudo solucionar la primer parte ("BUNDLE_TYPE" no se reconoce como un comando interno o externo) pero luego de esto queda trancado en "Watching files..."

![image](https://user-images.githubusercontent.com/54026070/63175473-7409e900-c01a-11e9-9d7f-164d3ceb10fd.png)

npm: v6.8.0
node: v10.10.0

**Comment by sgonzalez-orangeloops** [comment]
Hola Alexis! Muchas gracias por reportar estos errores. Hace unos días subimos una nueva versión del template que debería solucionarlos.
Vamos a cerrar el issue. Si aun encontrás problemas, comentanos!
